import type { ElementBox } from '@/model/ElementBox.js'

/** A visible, unstyled element at the origin; tests override what they measure. */
export const elementBox = (
  overrides: Partial<ElementBox> & { id: number },
): ElementBox => ({
  parent: null,
  tag: 'div',
  signature: 'div',
  selector: `#e${String(overrides.id)}`,
  x: 0,
  y: 0,
  width: 100,
  height: 20,
  text: '',
  textLength: 0,
  textTail: '',
  color: [17, 24, 39, 1],
  backgroundColor: [0, 0, 0, 0],
  hasBackgroundImage: false,
  disabled: false,
  borderWidths: [0, 0, 0, 0],
  borderColors: [null, null, null, null],
  overflowX: 'visible',
  overflowY: 'visible',
  position: 'static',
  flexWrap: 'nowrap',
  textOverflow: 'clip',
  scrollWidth: 100,
  clientWidth: 100,
  contentHeight: 20,
  lineBoxHeight: 0,
  contentWidth: 100,
  placeholderWidth: 0,
  transitionAll: false,
  svgDigest: '',
  svgPaint: '',
  shadowBlur: 0,
  scrollHeight: 20,
  clientHeight: 20,
  isControl: false,
  fontSize: 16,
  lineHeight: 24,
  letterSpacing: 0,
  fontWeight: 400,
  fontFamily: 'inter',
  fontVariantNumeric: 'normal',
  tabularDigits: true,
  textAlign: 'start',
  textTransform: 'none',
  lines: 0,
  borderRadius: 0,
  padding: [0, 0, 0, 0],
  isTextEntry: false,
  isDialog: false,
  label: '',
  isMain: false,
  isBanner: false,
  ...overrides,
})
