import { createBaseConfig } from '@busirocket/eslint-config/base'
import { createCodeQualityConfig } from '@busirocket/eslint-config/code-quality'
import { createTailwindConfig } from '@busirocket/eslint-config/tailwind'
import { createViteVueConfig } from '@busirocket/eslint-config/vite-vue'
import prettier from 'eslint-config-prettier'
import { globalIgnores } from 'eslint/config'
import path from 'node:path'
import tseslint from 'typescript-eslint'
// `withNuxt` is generated by `nuxt prepare` into `.nuxt/`. It returns a
// FlatConfigComposer that injects Nuxt-aware rules and the auto-import globals
// (ref, useState, defineNuxtConfig, defineEventHandler, ...) so our shared
// layers compose without tripping no-undef.
import withNuxt from './.nuxt/eslint.config.mjs'

// `.toConfigs()` resolves the composer to a plain flat-config array. ESLint 10's
// stricter config-array rejects the composer object itself during a full
// directory walk (`eslint .`), so we await it into an array up front.
// Layer order mirrors templates/vue-app:
// base -> vite-vue (vue + a11y + boundaries) -> code-quality -> tailwind -> prettier (last).
export default await withNuxt(
  // Nuxt's generated build output must never be linted; walking it also tripped
  // ESLint 10's config-array normalizer ("Unexpected function") during `eslint .`.
  globalIgnores(['.nuxt/**', '.output/**', '.data/**']),
  ...createBaseConfig({ tsconfigRootDir: import.meta.dirname }),
  ...createViteVueConfig({ tsconfigRootDir: import.meta.dirname }),
  ...createCodeQualityConfig(),
  ...createTailwindConfig(),
  {
    files: ['**/*.{ts,vue}'],
    settings: {
      tailwindcss: {
        config: path.join(import.meta.dirname, 'app/assets/css/main.css'),
      },
    },
  },
  // Declaration files require `interface` for module augmentation and mirror
  // upstream `any` generics — language constraints, not authored code.
  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
  // `<script setup>` top-level bindings are the component's reactive state, not
  // module-level helpers — the hidden-declaration rule does not apply to SFCs.
  {
    files: ['**/*.vue'],
    rules: {
      'code-policy/no-hidden-top-level-declarations': 'off',
    },
  },
  // Nuxt framework files default-export a config/handler object and may declare
  // setup-time bindings; Nuxt conventions require these shapes, so the
  // one-export / hidden-declaration policy is relaxed only for them.
  {
    files: [
      'nuxt.config.ts',
      'app/app.vue',
      'app/pages/**/*.vue',
      'app/plugins/**/*.ts',
      'server/**/*.ts',
    ],
    rules: {
      'code-policy/one-primary-unit': 'off',
      'code-policy/no-hidden-top-level-declarations': 'off',
    },
  },
  // Vue composables are the framework analogue of React hooks and live in the
  // conventional `composables/` folder; the placement rule is hook/React-centric.
  // Nuxt plugins must live in `plugins/` (a Nuxt convention), so a plugin named
  // `validateEnv.ts` cannot move to a `validators/` folder as the rule expects.
  // Nuxt auto-imports server helpers only from `server/utils/`, so that folder
  // name is mandated by the framework and the generic-folder ban cannot apply.
  {
    files: [
      'app/composables/**/*.ts',
      'app/plugins/**/*.ts',
      'server/utils/**/*.ts',
    ],
    rules: {
      'code-policy/file-kind-placement': 'off',
    },
  },
  // Nuxt file-based routing derives the route name from the filename, so a
  // top-level page like `index.vue` is single-word by design.
  {
    files: ['app/pages/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },
  // Root tooling configs and test files live outside the single tsconfig the
  // type-aware project service auto-discovers (Nuxt splits app/server/shared
  // into separate generated tsconfigs). Lint them without type information so
  // the project service does not reject them; `vue-tsc` still type-checks them.
  {
    files: [
      '*.config.ts',
      'eslint.config.ts',
      '**/*.{test,spec}.ts',
      'test/**/*.ts',
    ],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: { projectService: false, project: false },
    },
    rules: {
      'code-policy/one-primary-unit': 'off',
      'code-policy/no-hidden-top-level-declarations': 'off',
    },
  },
  // Disable formatting rules (incl. eslint-plugin-vue's) that conflict with Prettier. Must be last.
  prettier,
).toConfigs()
